### ISSUE TITLE
Model weights can not be downloaded from dropbox

### ISSUE THREAD

**Issue by NikolasMorshuis** [HJ-harry/DDS#4]
Hi,

It seems that the dropbox-links for the model weights and the example data are not valid anymore and lead to deleted files:

![image](https://github.com/user-attachments/assets/75e6d2bb-01df-40cc-8c2b-63f61babf29f)

Would it be possible to provide a new link or to re-upload the files?

**Comment by hyungjin-chung** [comment]
I posted a new link to the ckpts and data!

**Comment by kunkunzhou123** [comment]
Dear author，
Where is the new link？
